services:
  frontend:
    image: ghcr.io/byayex/queuequick-frontend:main
    expose:
      - "8080"
    networks:
      - proxy_network

  backend:
    image: ghcr.io/byayex/queuequick-backend:main
    expose:
      - "8090"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true