services:
  frontend:
    image: docker.pasi1337.de/docker-hosted/queuequick-frontend:main
    expose:
      - "8080"
    networks:
      - proxy_network

  backend:
    image: docker.pasi1337.de/docker-hosted/queuequick-backend:main
    expose:
      - "8090"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true