name: CI Workflow for QueueQuick

on:
#  push:
#    branches:
#      - main
#    tags:
#      - 'v*'  # Matches version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine Docker tag
      id: docker_tag
      run: |
        if [[ $GITHUB_REF == refs/heads/main ]]; then
          echo "tag=main" >> $GITHUB_ENV
        elif [[ $GITHUB_REF == refs/tags/v* ]]; then
          version=${GITHUB_REF#refs/tags/v}
          echo "tag=${version}" >> $GITHUB_ENV
        fi

    - name: Build and Push Docker images
      env:
        REGISTRY: ghcr.io
        IMAGE_TAG: ${{ env.tag }}
        REPO_NAME: ${{ github.repository_owner }}/queuequick
      run: |
        # Build frontend
        docker build -t $REGISTRY/$REPO_NAME-frontend:${IMAGE_TAG} ./frontend
        docker push $REGISTRY/$REPO_NAME-frontend:${IMAGE_TAG}

        # Build backend
        docker build -t $REGISTRY/$REPO_NAME-backend:${IMAGE_TAG} ./backend
        docker push $REGISTRY/$REPO_NAME-backend:${IMAGE_TAG}
