name: CI Workflow for QueueQuick

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # Matches version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Custom Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Determine Docker tag
      id: docker_tag
      run: |
        if [[ $GITHUB_REF == refs/heads/master ]]; then
          echo "tag=master" >> $GITHUB_ENV
        elif [[ $GITHUB_REF == refs/tags/v* ]]; then
          version=${GITHUB_REF#refs/tags/v}
          echo "tag=${version}" >> $GITHUB_ENV
        fi

    - name: Build and Push Docker images
      env:
        REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
        IMAGE_TAG: ${{ env.tag }}
      run: |
        # Build frontend
        docker build -t $REGISTRY_URL/queuequick-frontend:${IMAGE_TAG} ./frontend
        docker push $REGISTRY_URL/queuequick-frontend:${IMAGE_TAG}

        # Build backend
        docker build -t $REGISTRY_URL/queuequick-backend:${IMAGE_TAG} ./backend
        docker push $REGISTRY_URL/queuequick-backend:${IMAGE_TAG}
